winapi: Enable winerror feature
Somehow this wasn't a problem before, but an issue[0] triggered after
clap upgrade to 4.2.0:

    error[E0432]: unresolved import `winapi::shared::winerror`
    --> src\file.rs:11:21
    |
    11 | use winapi::shared::winerror::ERROR_NOT_SAME_DEVICE as xdev_err;
    |                     ^^^^^^^^ could not find `winerror` in `shared`

Looking at Cargo.lock, termcolor is no longer a dependency for clap, and
below that was a dependency for winapi-util, which seems to have papered
over this in the interim.

0: https://github.com/cdown/exifrename/actions/runs/4548478254/jobs/8019553218?pr=10